#############################################################################
# Generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#  Jul 18, 2020 08:01:58 AM WIB  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu {{}} -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 880x502
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Cashier"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr47 \
        -borderwidth 2 -relief groove -height 119 
    vTcl:DefineAlias "$top.tFr47" "Frame Inputan" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr47
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $site_3_0.tLa54 \
        -text Name -height 75 
    vTcl:DefineAlias "$site_3_0.tLa54" "lf_name" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.tLa54
    ttk::entry $site_4_0.tEn75 \
        -font TkTextFont -textvariable ev_nama -foreground {} \
        -background #727272 -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_4_0.tEn75" "e_name" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.tEn75 \
        -in $site_4_0 -x 0 -relx 0.04 -y 0 -rely 0.38 -width 0 \
        -relwidth 0.887 -height 0 -relheight 0.392 -anchor nw \
        -bordermode ignore 
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $site_3_0.tLa55 \
        -text Amount -height 75 
    vTcl:DefineAlias "$site_3_0.tLa55" "lf_amount" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.tLa55
    ttk::entry $site_4_0.tEn77 \
        -font TkTextFont -textvariable ev_jumlah -foreground {} \
        -background #727272 -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_4_0.tEn77" "e_amount" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.tEn77 \
        -in $site_4_0 -x 0 -relx 0.04 -y 0 -rely 0.38 -width 0 \
        -relwidth 0.888 -height 0 -relheight 0.392 -anchor nw \
        -bordermode ignore 
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $site_3_0.tLa56 \
        -text Price -height 75 
    vTcl:DefineAlias "$site_3_0.tLa56" "lf_price" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.tLa56
    ttk::entry $site_4_0.tEn78 \
        -font TkTextFont -textvariable ev_harga -foreground {} \
        -background #727272 -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_4_0.tEn78" "e_price" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.tEn78 \
        -in $site_4_0 -x 0 -relx 0.04 -y 0 -rely 0.38 -width 0 \
        -relwidth 0.888 -height 0 -relheight 0.392 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa54 \
        -in $site_3_0 -x 0 -relx 0.012 -y 0 -rely 0.153 -width 0 \
        -relwidth 0.31 -height 0 -relheight 0.603 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa55 \
        -in $site_3_0 -x 0 -relx 0.347 -y 0 -rely 0.153 -width 0 \
        -relwidth 0.31 -height 0 -relheight 0.603 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa56 \
        -in $site_3_0 -x 0 -relx 0.682 -y 0 -rely 0.153 -width 0 \
        -relwidth 0.31 -height 0 -relheight 0.603 -anchor nw \
        -bordermode ignore 
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr50 \
        -borderwidth 2 -relief groove -height 323 
    vTcl:DefineAlias "$top.tFr50" "frame_btn" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr50
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu62 \
        -command add -takefocus {} -text Add -cursor X_cursor 
    vTcl:DefineAlias "$site_3_0.tBu62" "btn_add" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu72 \
        -command remove -takefocus {} -text Remove -cursor X_cursor 
    vTcl:DefineAlias "$site_3_0.tBu72" "btn_remove" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu73 \
        -command export -takefocus {} -text Export -cursor X_cursor 
    vTcl:DefineAlias "$site_3_0.tBu73" "btn_exp" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu74 \
        -command exit -takefocus {} -text Exit -cursor X_cursor 
    vTcl:DefineAlias "$site_3_0.tBu74" "btn_exit" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $site_3_0.tLa89 \
        -text Total -width 110 -height 55 -takefocus 0 
    vTcl:DefineAlias "$site_3_0.tLa89" "lt_tota" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.tLa89
    label $site_4_0.lab90 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -textvariable ev_total 
    vTcl:DefineAlias "$site_4_0.lab90" "l_total" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab90 \
        -in $site_4_0 -x 0 -relx 0.091 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.809 -height 0 -relheight 0.382 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu62 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.029 -width 103 \
        -relwidth 0 -height 28 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu72 \
        -in $site_3_0 -x 0 -relx 0.079 -y 0 -rely 0.164 -width 103 \
        -relwidth 0 -height 28 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu73 \
        -in $site_3_0 -x 0 -relx 0.079 -y 0 -rely 0.295 -width 103 \
        -relwidth 0 -height 28 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu74 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.899 -width 113 \
        -relwidth 0 -height 28 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa89 \
        -in $site_3_0 -x 0 -relx 0.075 -y 0 -rely 0.696 -width 0 \
        -relwidth 0.827 -height 0 -relheight 0.159 -anchor nw \
        -bordermode ignore 
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr69 \
        -borderwidth 2 -relief groove -height 305 -takefocus 0 
    vTcl:DefineAlias "$top.tFr69" "frame_treeview" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr69
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_3_0.scr81 \
        -background $vTcl(actual_gui_bg) -height 15 -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_3_0.scr81" "trv" vTcl:WidgetProc "Toplevel1" 1

    .top43.tFr69.scr81.01 configure -columns "Col1 Col2 Col3" \
        -height 4 \
        -takefocus 0
        .top43.tFr69.scr81.01 configure -columns {Col1 Col2 Col3}
        .top43.tFr69.scr81.01 heading #0 -text {Name}
        .top43.tFr69.scr81.01 heading #0 -anchor center
        .top43.tFr69.scr81.01 column #0 -width 176
        .top43.tFr69.scr81.01 column #0 -minwidth 20
        .top43.tFr69.scr81.01 column #0 -stretch 1
        .top43.tFr69.scr81.01 column #0 -anchor w
        .top43.tFr69.scr81.01 heading Col1 -text {Amount}
        .top43.tFr69.scr81.01 heading Col1 -anchor center
        .top43.tFr69.scr81.01 column Col1 -width 176
        .top43.tFr69.scr81.01 column Col1 -minwidth 20
        .top43.tFr69.scr81.01 column Col1 -stretch 1
        .top43.tFr69.scr81.01 column Col1 -anchor w
        .top43.tFr69.scr81.01 heading Col2 -text {Price}
        .top43.tFr69.scr81.01 heading Col2 -anchor center
        .top43.tFr69.scr81.01 column Col2 -width 170
        .top43.tFr69.scr81.01 column Col2 -minwidth 20
        .top43.tFr69.scr81.01 column Col2 -stretch 1
        .top43.tFr69.scr81.01 column Col2 -anchor w
        .top43.tFr69.scr81.01 heading Col3 -text {Total}
        .top43.tFr69.scr81.01 heading Col3 -anchor center
        .top43.tFr69.scr81.01 column Col3 -width 164
        .top43.tFr69.scr81.01 column Col3 -minwidth 20
        .top43.tFr69.scr81.01 column Col3 -stretch 1
        .top43.tFr69.scr81.01 column Col3 -anchor center
    vTcl:copy_lock $site_3_0.scr81
    place $site_3_0.scr81 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.98 -height 0 \
        -relheight 0.971 -anchor nw -bordermode ignore 
    ttk::separator $top.tSe83 \
        -takefocus 0 
    vTcl:DefineAlias "$top.tSe83" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe84 \
        -orient vertical -takefocus 0 
    vTcl:DefineAlias "$top.tSe84" "TSeparator2" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr47 \
        -in $top -x 0 -relx 0.013 -y 0 -rely 0.022 -width 0 -relwidth 0.98 \
        -height 0 -relheight 0.238 -anchor nw -bordermode ignore 
    place $top.tFr50 \
        -in $top -x 0 -relx 0.841 -y 0 -rely 0.299 -width 0 -relwidth 0.151 \
        -height 0 -relheight 0.687 -anchor nw -bordermode ignore 
    place $top.tFr69 \
        -in $top -x 0 -relx 0.013 -y 0 -rely 0.311 -width 0 -relwidth 0.811 \
        -height 0 -relheight 0.678 -anchor nw -bordermode ignore 
    place $top.tSe83 \
        -in $top -x 0 -relx 0.012 -y 0 -rely 0.28 -width 0 -relwidth 0.98 \
        -height 0 -relheight 0.004 -anchor nw -bordermode inside 
    place $top.tSe84 \
        -in $top -x 0 -relx 0.83 -y 0 -rely 0.281 -height 0 -relheight 0.699 \
        -anchor nw -bordermode inside 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

